repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0  # Use the latest release
    hooks:
      - id: ruff
        name: ruff (lint + format)
        args: [--fix, --select, ALL]
