name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Install uv
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      # Add uv to PATH
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Setup Python (match your project version, e.g. 3.11)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Install dependencies from pyproject.toml
      - name: Sync dependencies
        run: uv sync --all-extras --dev

      # Run lint (flake8 or ruff if configured)
      - name: Run lint
        run: uv run ruff check .

      # Run tests (pytest by default)
      # - name: Run tests
      #   run: uv run pytest -v
