name: Price Scraper

on:
  workflow_dispatch: # run manually
  schedule:
    - cron: "0 5 * * *" # every day at 5 AM

jobs:
  run-on-pi:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ runner.arch }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install Playwright Chromium
        run: uv run playwright install chromium

      - name: Run Price Scraper
        run: uv run python main.py
