name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  run-on-pi:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH   # add uv to PATH

      - name: Verify uv works
        run: uv --version

      - name: Restart scraper
        run: |
          systemctl --user restart price_scraper.service || true
